title: Ideas Come from Confluence
author:
  name: Pauline
 
description: > # this means to ignore newlines until "show_excerpts:"
  Nothing new, nothing so special but a real human being interacting with others and the outside world. Secretly pushing a rock up a mountain.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
   
    - { platform: instagram,      user_url: "" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/pauline-zhong-0203a11a3/" }
  

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
